// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm5wHftLqKmKqJEyKy_rCdN9ky7FGIBjo',
    appId: '1:527235376632:web:2af99b7b351f2fd411e20d',
    messagingSenderId: '527235376632',
    projectId: 'apti-clear',
    databaseURL: 'https://apti-clear-default-rtdb.firebaseio.com/',
    authDomain: 'apti-clear.firebaseapp.com',
    storageBucket: 'apti-clear.firebasestorage.app',
    measurementId: 'G-LNM0SG7FQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9YfQOrSWvX9nYyPlz2EzIpNrTGzpYWRA',
    appId: '1:527235376632:android:d5ebdf022c5c555c11e20d',
    messagingSenderId: '527235376632',
    projectId: 'apti-clear',
    storageBucket: 'apti-clear.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx0RUNsNKDglwXr5PvuXZlqqlVFDTHUTQ',
    appId: '1:527235376632:ios:4077a1bdd9380ddd11e20d',
    messagingSenderId: '527235376632',
    projectId: 'apti-clear',
    storageBucket: 'apti-clear.firebasestorage.app',
    iosBundleId: 'com.example.apticlear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx0RUNsNKDglwXr5PvuXZlqqlVFDTHUTQ',
    appId: '1:527235376632:ios:4077a1bdd9380ddd11e20d',
    messagingSenderId: '527235376632',
    projectId: 'apti-clear',
    storageBucket: 'apti-clear.firebasestorage.app',
    iosBundleId: 'com.example.apticlear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm5wHftLqKmKqJEyKy_rCdN9ky7FGIBjo',
    appId: '1:527235376632:web:6cc27126b6f7c9fc11e20d',
    databaseURL: 'https://apti-clear-default-rtdb.firebaseio.com/',
    messagingSenderId: '527235376632',
    projectId: 'apti-clear',
    authDomain: 'apti-clear.firebaseapp.com',
    storageBucket: 'apti-clear.firebasestorage.app',
    measurementId: 'G-MQMBEK2C8S',
  );
}
